## Easy Criptography with Python

Pedro Garcia. MIT License.

Having the following simple letter to number conversion

A=1
B=2
C=3
D=4
E=5
F=6
G=7
H=8
I=9
J=10
K=11
L=12
M=13
N=14
Ñ=15
O=16
P=17
Q=18
R=19
S=20
T=21
U=22
V=23
W=24
X=25
Y=26
Z=27
space=28


Let's encrypt the following spanish sentence (Linear Algebra with Python)

'ALGEBRA LINEAL CON PYTHON'  
1 12 7 5 2 19 1 28 12 9 14 5 1 12 18 3 16 14 28 17 26 21 8 16 14  

As we are going to use a 3x3 matrix, grouped the numbers in three sets, and if more numbers are needed for completing, we use zeroes.

(1,12,7) (5,2,19) (1,28,12) (9,14,5) (1,12,18) (3,16,14) (28,17,26) (21,8,16) (14,0,0)  

The transformation to apply (the key) is:
$A=
  \left[ {\begin{array}{cc}
   2 & 5 & 3\\
   1 & 3 & 2\\
   3 & 6 & 4\\
  \end{array} } \right]$

Let's discover the message and how to decrypt it
  

**METHOD 1. THE EASY ALGEBRAIC METHOD** (ZERO SOPHISTICATED)

In [1]:
import numpy as np

#the matrix transformation, the key
key=np.array([
   [2,5,3],
   [1,3,2],
   [3,6,4]
   ])

message=np.matrix([
   [1,5,1,9,1,3,28,21,14],
   [12,2,28,14,12,16,17,8,0],
   [7,19,12,5,18,14,26,16,0]
])

print("Message before encryption", message)

#encrypt the message
messageEncrypted=key*message
print("Encrypted message:", messageEncrypted)

#key's inverse matrix for decrypt the message
keyInverseMatrix = np.matrix.round(np.linalg.inv(key))

#Decrypt the message
originalMessage = keyInverseMatrix * messageEncrypted
print("Decrypted Message", originalMessage)

Message before encryption [[ 1  5  1  9  1  3 28 21 14]
 [12  2 28 14 12 16 17  8  0]
 [ 7 19 12  5 18 14 26 16  0]]
Encrypted message: [[ 83  77 178 103 116 128 219 130  28]
 [ 51  49 109  61  73  79 131  77  14]
 [103 103 219 131 147 161 290 175  42]]
Decrypted Message [[ 1.  5.  1.  9.  1.  3. 28. 21. 14.]
 [12.  2. 28. 14. 12. 16. 17.  8.  0.]
 [ 7. 19. 12.  5. 18. 14. 26. 16.  0.]]


**METHOD 2. WITH A BASIC CRYPTOSYSTEM** (HILL MATRIX CYPHERER)

STEP 1. Create a dictionary with the key:value relationship between the alphabet's letters and numbers. The 0 is needed because it could be a value in the matrix. 

In [2]:
dictionary={'A':1, 'B':2, 'C':3, 'D':4, 'E':5, 'F':6, 'G':7, 'H':8, 'I':9, 'J':10, 'K':11, 'L':12, 'M':13, 
             'N':14, 'Ñ':15, 'O':16, 'P':17, 'Q':18, 'R':19, 'S':20, 'T':21, 'U':22, 'V':23, 'W':24, 'X':25,
             'Y':26, 'Z':27, ' ':28, '':0}

STEP 2. The message and the key. If we use other matrix's dimensions, for algortihm reusability, we need to know the matrix's size.

In [22]:
message='LINEAR ALGEBRA WITH PYTHON'
#message='ALGEBRA LINEAL CON PYTHON'

#key
import numpy as np
key=np.matrix([
   [2,5,3],
   [1,3,2],
   [3,6,4]
   ])

#we need to keep the matrix's shape
matrixSize=key.shape
print("Key's matrix size: ", matrixSize)

Key's matrix size:  (3, 3)


STEP 3. Letter to Number, Number to Letter functions.

In [18]:
#get the number by letter
def letterToNumber(letter):
    return dictionary[letter]

#get letter by number
def numberToLetter(number):
    return (list(dictionary.keys())[list(dictionary.values()).index(int(number))])

STEP 4. Function that transform the message into a matrix. It does in function of the message's size and matrix's size.

In [19]:
def messageToMatrix(message,keyMessageSize):
    
    messageSize=len(message)
    
    #number of zeroes for completing the matrix in case the message size does not
    #fit perfectly with the matrix's size
    zeroesToFill=3-messageSize%keyMessageSize
    
    #number of matrix columns
    matrixColumns=int((messageSize+(zeroesToFill))/keyMessageSize)
    
    messageNumbered =[]
    messageMatrix=np.zeros([keyMessageSize,matrixColumns])

    #message to array of numbers
    for i in range(len(message)):
        messageNumbered=np.append(messageNumbered,letterToNumber(message[i]))

    #complete to zeroes
    for j in range(zeroesToFill):
        messageNumbered=np.append(messageNumbered,0)
    
    #build the matrix
    for z in range(keyMessageSize):
        messageMatrix[z]=messageNumbered[matrixColumns*z:matrixColumns*(z+1)]

    return messageMatrix

STEP 5. Matrix to text function.

In [20]:
def matrixToText(matrix):
    matrixSize=matrix.shape
    rows=matrixSize[0]
    columns=matrixSize[1]
    text=''
    
    for i in range(rows):
        for n in range(columns):
            text=text+numberToLetter(matrix[i,n])
            
    return text

STEP 6. Message encryption.

In [24]:
res=messageToMatrix(message,matrixSize[0])

print("************* ENCRYPTION'S START **************")
print("Message's Matrix ", res)

#encrypt the message
messageEncrypted=key*res

print("************* **************")
print("Encrypted message:", messageEncrypted)

#as we do not have in the dictionary vaules greater than 29, we have to normalize to 29
#applying the module of 29
messageEncryptedNormalized=messageEncrypted%29
print("************* **************")
print("Encrypted message normalized:", messageEncryptedNormalized)

#show the message encrypted
print("************* **************")
print("Message encrypted:",matrixToText(messageEncryptedNormalized))

************* ENCRYPTION'S START **************
Message's Matrix  [[12.  9. 14.  5.  1. 19. 28.  1. 12.]
 [ 7.  5.  2. 19.  1. 28. 24.  9. 21.]
 [ 8. 28. 17. 26. 21.  8. 16. 14.  0.]]
************* **************
Encrypted message: [[ 83. 127.  89. 183.  70. 202. 224.  89. 129.]
 [ 49.  80.  54. 114.  46. 119. 132.  56.  75.]
 [110. 169. 122. 233.  93. 257. 292. 113. 162.]]
************* **************
Encrypted message normalized: [[25. 11.  2.  9. 12. 28. 21.  2. 13.]
 [20. 22. 25. 27. 17.  3. 16. 27. 17.]
 [23. 24.  6.  1.  6. 25.  2. 26. 17.]]
************* **************
Message encrypted: XKBIL TBMSUXZPCOZPVWFAFXBYP


STEP 7. Decrypt the message. This method is based on the Hill's matrix encrypt method.

In [25]:
print("************* DECRYPTION'S START **************")

#we need to know the key's determinant value, pass it to module of 29
keyDeterminantValue=int(np.linalg.det(key))
print("Key's determinant value: ", keyDeterminantValue)

x= keyDeterminantValue%29
print("************* **************")
print("Key's determinant value with module 29: ",x)

#key's inverse matrix for decrypt the message
keyInverseMatrix = np.matrix.round(np.linalg.inv(key))
print("************* **************")
print("Key's inverse matrix:", keyInverseMatrix)

keyInverseDeterminantValue=int(np.linalg.det(keyInverseMatrix))
print("************* **************")
print("Key's inverse determinant value: ", keyInverseDeterminantValue)

#get the original message applying module of 29 to the key's inverse matrix,
#multiply it by the matrix that holds the ecrypted message
#apply to all the module of 29
originalMessage = (keyInverseMatrix%29 * messageEncryptedNormalized)%29
print("************* **************")
print("Decrypted marix's message", originalMessage)

print("************* **************")
print("Decrypted message:",matrixToText(originalMessage))

************* DECRYPTION'S START **************
Key's determinant value:  1
************* **************
Key's determinant value with module 29:  1
************* **************
Key's inverse matrix: [[-0. -2.  1.]
 [ 2. -1. -1.]
 [-3.  3.  1.]]
************* **************
Key's inverse determinant value:  0
************* **************
Decrypted marix's message [[12.  9. 14.  5.  1. 19. 28.  1. 12.]
 [ 7.  5.  2. 19.  1. 28. 24.  9. 21.]
 [ 8. 28. 17. 26. 21.  8. 16. 14.  0.]]
************* **************
Decrypted message: LINEAR ALGEBRA WITH PYTHON
